(function(){'use strict';
function g(a){return function(b){this[a]=b}}function h(a){return function(){return this[a]}}function m(a){return function(){return a}}var p,r="object"===typeof __ScalaJSEnv&&__ScalaJSEnv?__ScalaJSEnv:{},t="object"===typeof r.global&&r.global?r.global:"object"===typeof global&&global&&global.Object===Object?global:this;r.global=t;var aa="object"===typeof r.exportsNamespace&&r.exportsNamespace?r.exportsNamespace:t;r.exportsNamespace=aa;t.Object.freeze(r);
var ba={semantics:{asInstanceOfs:2,moduleInit:2,strictFloats:!1,productionMode:!0},assumingES6:!1};t.Object.freeze(ba);t.Object.freeze(ba.semantics);
var v=t.Math.imul||function(a,b){var c=a&65535,e=b&65535;return c*e+((a>>>16&65535)*e+c*(b>>>16&65535)<<16>>>0)|0},w=t.Math.fround||function(a){return+a},ca=t.Math.clz32||function(a){if(0===a)return 32;var b=1;0===(a&4294901760)&&(a<<=16,b+=16);0===(a&4278190080)&&(a<<=8,b+=8);0===(a&4026531840)&&(a<<=4,b+=4);0===(a&3221225472)&&(a<<=2,b+=2);return b+(a>>31)},ea=0,fa=t.WeakMap?new t.WeakMap:null;function ga(a){return function(b,c){return!(!b||!b.b||b.b.Ga!==c||b.b.Ea!==a)}}
function ha(a){for(var b in a)return b}function x(a,b){return ia(a,b,0)}function ia(a,b,c){var e=new a.tb(b[c]);if(c<b.length-1){a=a.Ka;c+=1;for(var d=e.d,k=0;k<d.length;k++)d[k]=ia(a,b,c)}return e}function ja(a){return void 0===a?"undefined":a.toString()}
function ka(a){switch(typeof a){case "string":return z(la);case "number":var b=a|0;return b===a?b<<24>>24===b&&1/b!==1/-0?z(ma):b<<16>>16===b&&1/b!==1/-0?z(na):z(oa):"number"===typeof a?z(pa):z(qa);case "boolean":return z(ra);case "undefined":return z(sa);default:return null===a?a.di():ta(a)?z(ua):a&&a.b?z(a.b):null}}
function va(a){switch(typeof a){case "string":return wa(A(),a);case "number":return xa(ya(),a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.b||null===a?a.B():null===fa?42:za(a)}}function Aa(a){return 2147483647<a?2147483647:-2147483648>a?-2147483648:a|0}function Ba(a,b){for(var c=t.Object.getPrototypeOf,e=t.Object.getOwnPropertyDescriptor,d=c(a);null!==d;){var k=e(d,b);if(void 0!==k)return k;d=c(d)}}
function Ca(a,b,c){a=Ba(a,c);if(void 0!==a)return c=a.get,void 0!==c?c.call(b):a.value}function Da(a,b,c,e){a=Ba(a,c);if(void 0!==a&&(a=a.set,void 0!==a)){a.call(b,e);return}throw new t.TypeError("super has no setter '"+c+"'.");}
var za=null!==fa?function(a){switch(typeof a){case "string":case "number":case "boolean":case "undefined":return va(a);default:if(null===a)return 0;var b=fa.get(a);void 0===b&&(ea=b=ea+1|0,fa.set(a,b));return b}}:function(a){if(a&&a.b){var b=a.$idHashCode$0;if(void 0!==b)return b;if(t.Object.isSealed(a))return 42;ea=b=ea+1|0;return a.$idHashCode$0=b}return null===a?0:va(a)};this.__ScalaJSExportsNamespace=aa;
function Ea(){this.kb=this.tb=void 0;this.Ea=this.Ka=this.L=null;this.Ga=0;this.mc=null;this.bb="";this.K=this.$a=this.ab=void 0;this.name="";this.isRawJSType=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function Fa(a,b,c){var e=new Ea;e.L={};e.Ka=null;e.mc=a;e.bb=b;e.K=m(!1);e.name=c;e.isPrimitive=!0;e.isInstance=m(!1);return e}
function B(a,b,c,e,d,k,n){var f=new Ea,l=ha(a);k=k||function(a){return!!(a&&a.b&&a.b.L[l])};n=n||function(a,b){return!!(a&&a.b&&a.b.Ga===b&&a.b.Ea.L[l])};f.kb=d;f.L=c;f.bb="L"+b+";";f.K=n;f.name=b;f.isInterface=!1;f.isRawJSType=!!e;f.isInstance=k;return f}
function Ga(a){function b(a){if("number"===typeof a){this.d=Array(a);for(var b=0;b<a;b++)this.d[b]=d}else this.d=a}var c=new Ea,e=a.mc,d="longZero"==e?Ha().ha:e;b.prototype=new C;b.prototype.b=c;var e="["+a.bb,k=a.Ea||a,n=a.Ga+1;c.tb=b;c.kb=D;c.L={c:1,Vc:1,e:1};c.Ka=a;c.Ea=k;c.Ga=n;c.mc=null;c.bb=e;c.ab=void 0;c.$a=void 0;c.K=void 0;c.name=e;c.isPrimitive=!1;c.isInterface=!1;c.isArrayClass=!0;c.isInstance=function(a){return k.K(a,n)};return c}
function z(a){if(!a.ab){var b=new Ia;b.db=a;a.ab=b}return a.ab}function E(a){a.$a||(a.$a=Ga(a));return a.$a}Ea.prototype.getFakeInstance=function(){return this===la?"some string":this===ra?!1:this===ma||this===na||this===oa||this===pa||this===qa?0:this===ua?Ha().ha:this===sa?void 0:{b:this}};Ea.prototype.getSuperclass=function(){return this.kb?z(this.kb):null};Ea.prototype.getComponentType=function(){return this.Ka?z(this.Ka):null};
Ea.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b=E(b);return x(b,a)};var Ka=Fa(!1,"Z","boolean"),La=Fa(0,"C","char"),Ma=Fa(0,"B","byte"),Na=Fa(0,"S","short"),Oa=Fa(0,"I","int"),Pa=Fa("longZero","J","long"),Qa=Fa(0,"F","float"),Ra=Fa(0,"D","double");Ka.K=ga(Ka);La.K=ga(La);Ma.K=ga(Ma);Na.K=ga(Na);Oa.K=ga(Oa);Pa.K=ga(Pa);Qa.K=ga(Qa);Ra.K=ga(Ra);function Sa(){}function C(){}C.prototype=Sa.prototype;Sa.prototype.a=function(){return this};Sa.prototype.k=function(){var a=Ta(ka(this)),b=(+(this.B()>>>0)).toString(16);return a+"@"+b};Sa.prototype.B=function(){return za(this)};Sa.prototype.toString=function(){return this.k()};var D=B({c:0},"java.lang.Object",{c:1},void 0,void 0,function(a){return null!==a},function(a,b){var c=a&&a.b;if(c){var e=c.Ga||0;return!(e<b)&&(e>b||!c.Ea.isPrimitive)}return!1});Sa.prototype.b=D;
function G(){this.q=this.cb=this.Ca=null}G.prototype=new C;G.prototype.constructor=G;G.prototype.Fb=function(a,b){this.Ca=a;this.cb=b;this.q=(new Ua).Fb(a,b);return this};
G.prototype.drawOnCanvas=function(a,b,c){var e=!!a;b=!!b;a=!!c;H(I(),this.cb).drawImage(this.Ca,0,0,this.cb.width|0,this.cb.height|0);c=this.q;if(e||b||a){0===c.x&&(c.Z=Va(c),c.Y=Va(c),c.q=x(E(Ka),[v(c.Z.width|0,c.Z.height|0)]),c.x=c.Z.width|0);H(I(),c.Y).drawImage(c.Ca,0,0,c.Y.width|0,c.Y.height|0);var d=H(I(),c.Y).getImageData(0,0,c.Y.width|0,c.Y.height|0).data,k=H(I(),c.Z).getImageData(0,0,c.Z.width|0,c.Z.height|0).data,n=k.length|0,f=0>=n;if(f)var l=0;else var l=n/4|0,u=0!==(n%4|0)?1:0,l=0<l&&
0<u&&0>(l+u|0)?-1:l+u|0;f?f=-4:(f=n%4|0,f=0!==f?n-f|0:-4+n|0);f=4+f|0;0>l&&Wa(J(),0,n,4);for(n=0;n!==f;){var l=n,q=w(255+w(d[l]|0)),s=w(255+w(d[1+l|0]|0)),y=w(255+w(d[2+l|0]|0)),W=w(255+w(k[l]|0)),M=w(255+w(k[1+l|0]|0)),X=w(255+w(k[2+l|0]|0)),u=c.q;w(w(q/s)/w(W/M))>c.vb&&w(w(q/s)/w(W/M))<c.ub&&w(w(s/y)/w(M/X))>c.vb&&w(w(s/y)/w(M/X))<c.ub?(q=(d[l]|0)-(k[l]|0)|0,q=(0>q?-q|0:q)<c.eb):q=!1;q?(q=(d[1+l|0]|0)-(k[1+l|0]|0)|0,q=(0>q?-q|0:q)<c.eb):q=!1;q?(q=(d[2+l|0]|0)-(k[2+l|0]|0)|0,q=(0>q?-q|0:q)<c.eb):
q=!1;u.d[l/4|0]=q;n=4+n|0}for(d=1;3!==d;){l=c.x;n=c.q.d.length-c.x|0;k=(f=l>=n)?0:Xa(Ya((new K).o(n),(new K).o(l)))?-1:n-l|0;f=1+(f?-1+l|0:-1+n|0)|0;0>k&&Wa(J(),l,n,1);n=-2147483648!==l||-2147483648!==n;for(u=0;n?l!==f:u<k;)q=l,s=q%c.x|0,y=q/c.x|0,(c.q.d[(-1+s|0)+v(y,c.x)|0]&&c.q.d[(1+s|0)+v(y,c.x)|0]||c.q.d[s+v(-1+y|0,c.x)|0]&&c.q.d[s+v(1+y|0,c.x)|0])&&(c.q.d[q]=!0),(c.q.d[(-1+s|0)+v(y,c.x)|0]||c.q.d[(1+s|0)+v(y,c.x)|0])&&(c.q.d[s+v(-1+y|0,c.x)|0]||c.q.d[s+v(1+y|0,c.x)|0])||(c.q.d[q]=!1),u=1+u|0,
l=1+l|0;d=1+d|0}}if(e){e=H(I(),c.v).getImageData(0,0,c.v.width|0,c.v.height|0);d=e.data;f=c.q.d.length;n=0>=f;k=1+(n?-1:-1+f|0)|0;0>(n?0:f)&&Wa(J(),0,f,1);for(f=0;f!==k;){l=f;s=v(l%c.x|0,c.M);n=v(l/c.x|0,c.M);if(c.q.d[l])for(q=s+c.M|0,l=(u=s>=q)?0:Xa(Ya((new K).o(q),(new K).o(s)))?-1:q-s|0,u=1+(u?-1+s|0:-1+q|0)|0,0>l&&Wa(J(),s,q,1),q=-2147483648!==s||-2147483648!==q,y=0;q?s!==u:y<l;){var W=s,F=n+c.M|0,M=(X=n>=F)?0:Xa(Ya((new K).o(F),(new K).o(n)))?-1:F-n|0,X=1+(X?-1+n|0:-1+F|0)|0;0>M&&Wa(J(),n,F,
1);for(var F=-2147483648!==n||-2147483648!==F,Y=n,Ja=0;F?Y!==X:Ja<M;){var da=v(4,W+v(Y,c.v.width|0)|0);d[da]=0;d[1+da|0]=200;d[2+da|0]=0;Ja=1+Ja|0;Y=1+Y|0}y=1+y|0;s=1+s|0}f=1+f|0}H(I(),c.v).putImageData(e,0,0)}if(a){e=Za(c,0,100);if(null!==e)a=e.oa,e=e.pa;else throw(new L).N(e);k=Za(c,2,100);if(null!==k)d=k.oa,f=k.pa;else throw(new L).N(k);k=a-d;f=e-f;d=15*+t.Math.sqrt(k*k+f*f);k=-1.5707963267948966+ +t.Math.atan2(-f,-k);if(1500>d&&100<d){c.Pa||(c.Jb.play(),c.Ib.play(),c.Pa=!0);if(1.0471975511965976<
+t.Math.abs(c.Qa.d[c.Oa]-k))for(f=c.Kb,$a||($a=(new ab).a()),n=$a,l=c.Kb.X(),f.qa(bb(n.gc,l)).play(),f=0;10!==f;)c.Qa.d[f]=k,f=1+f|0;c.Qa.d[c.Oa]=k;c.Oa=(1+c.Oa|0)%c.Qa.d.length|0;H(I(),c.v).save();H(I(),c.v).translate(a,e);H(I(),c.v).rotate(k);H(I(),c.v).drawImage(c.Gb,-d/8,-d,d/4,d);H(I(),c.v).drawImage(c.Hb,-d/24,-d/8,d/12,d/4);H(I(),c.v).restore()}else c.Pa&&(c.Jb.play(),c.Ib.stop(),c.Pa=!1)}if(b){a=Za(c,0,130);if(null!==a)b=a.oa,a=a.pa;else throw(new L).N(a);t.drawFireball(c.v,Aa(b),Aa(a))}};
G.prototype.b=B({Md:0},"arjs.Camera",{Md:1,c:1});aa.arjs=aa.arjs||{};aa.arjs.Camera=function(a,b){var c=new G;G.prototype.Fb.call(c,a,b);return c};aa.arjs.Camera.prototype=G.prototype;function Ua(){this.v=this.Ca=null;this.M=this.ub=this.vb=this.eb=0;this.q=this.Y=this.Z=null;this.x=0;this.gf=this.Kb=this.Ib=this.Jb=this.Hb=this.Gb=null;this.Pa=!1;this.Qa=null;this.Oa=0}Ua.prototype=new C;Ua.prototype.constructor=Ua;
Ua.prototype.Fb=function(a,b){this.Ca=a;this.v=b;this.eb=35;this.vb=0.85;this.ub=1.15;this.M=5;this.q=this.Y=this.Z=null;this.x=0;this.Gb=cb().createElement("img");this.Gb.src="imgs/ls.png";this.Hb=cb().createElement("img");this.Hb.src="imgs/ls-base.png";this.Jb=t.eval("new Howl({ urls: ['snd/SaberOn.wav'] })");this.Ib=t.eval("new Howl({ urls: ['snd/Hum.wav'], loop: true })");db||(db=(new eb).a());fb();db||(db=(new eb).a());gb();for(var c=(new hb).a(),e=1;7!==e;){var d=ib(jb(new kb,lb(new N,["new Howl({ urls: ['snd/Swing0",
".wav'] })"])),lb(new N,[e])),k=t.eval(d),d=c;if(d.ja>=d.Ma.d.length){var n=32+d.Ha|0,f=d,l=n,u=d.Ha^n;if(1024>u)1===f.D()&&(f.l(x(E(D),[32])),f.f().d[0]=f.s(),f.aa(1+f.D()|0)),f.m(x(E(D),[32])),f.f().d[31&l>>5]=f.s();else if(32768>u)2===f.D()&&(f.t(x(E(D),[32])),f.h().d[0]=f.f(),f.aa(1+f.D()|0)),f.m(x(E(D),[32])),f.l(x(E(D),[32])),f.f().d[31&l>>5]=f.s(),f.h().d[31&l>>10]=f.f();else if(1048576>u)3===f.D()&&(f.A(x(E(D),[32])),f.j().d[0]=f.h(),f.aa(1+f.D()|0)),f.m(x(E(D),[32])),f.l(x(E(D),[32])),f.t(x(E(D),
[32])),f.f().d[31&l>>5]=f.s(),f.h().d[31&l>>10]=f.f(),f.j().d[31&l>>15]=f.h();else if(33554432>u)4===f.D()&&(f.R(x(E(D),[32])),f.w().d[0]=f.j(),f.aa(1+f.D()|0)),f.m(x(E(D),[32])),f.l(x(E(D),[32])),f.t(x(E(D),[32])),f.A(x(E(D),[32])),f.f().d[31&l>>5]=f.s(),f.h().d[31&l>>10]=f.f(),f.j().d[31&l>>15]=f.h(),f.w().d[31&l>>20]=f.j();else if(1073741824>u)5===f.D()&&(f.Na(x(E(D),[32])),f.S().d[0]=f.w(),f.aa(1+f.D()|0)),f.m(x(E(D),[32])),f.l(x(E(D),[32])),f.t(x(E(D),[32])),f.A(x(E(D),[32])),f.R(x(E(D),[32])),
f.f().d[31&l>>5]=f.s(),f.h().d[31&l>>10]=f.f(),f.j().d[31&l>>15]=f.h(),f.w().d[31&l>>20]=f.j(),f.S().d[31&l>>25]=f.w();else throw(new O).a();d.Ha=n;d.ja=0}d.Ma.d[d.ja]=k;d.ja=1+d.ja|0;e=1+e|0}e=c.Ha+c.ja|0;0===e?c=gb().sc:(d=(new mb).Eb(0,e,0),nb(d,c,c.La),1<c.La&&ob(d,0,-1+e|0),c=d);this.Kb=c;this.gf=t.eval("new Howl({ urls: ['snd/Hum.wav'], loop: true })");this.Pa=!1;c=[];for(e=0;15>e;)c.push(0),e=1+e|0;this.Qa=new (E(Ra).tb)(c);this.Oa=0;return this};
function Za(a,b,c){var e=0,d=e=0,k=d=0,k=0,n=H(I(),a.v).getImageData(0,0,a.v.width|0,a.v.height|0).data,f=a.q.d.length,l=0>=f,u=1+(l?-1:-1+f|0)|0;0>(l?0:f)&&Wa(J(),0,f,1);for(f=0;f!==u;){var q=f,s=v(q%a.x|0,a.M),l=v(q/a.x|0,a.M);if(!a.q.d[q]){var y=s+a.M|0,W=s>=y,q=W?0:Xa(Ya((new K).o(y),(new K).o(s)))?-1:y-s|0,W=1+(W?-1+s|0:-1+y|0)|0;0>q&&Wa(J(),s,y,1);for(var y=-2147483648!==s||-2147483648!==y,M=0;y?s!==W:M<q;){var X=s,F=l+a.M|0,Y=l>=F,Ja=Y?0:Xa(Ya((new K).o(F),(new K).o(l)))?-1:F-l|0,Y=1+(Y?-1+
l|0:-1+F|0)|0;0>Ja&&Wa(J(),l,F,1);for(var F=-2147483648!==l||-2147483648!==F,da=l,Fd=0;F?da!==Y:Fd<Ja;){var lf=da,lc=v(4,X+v(lf,a.v.width|0)|0),Gd=n[lc+(b%3|0)|0]|0,kg=n[lc+((1+b|0)%3|0)|0]|0,lc=n[lc+((2+b|0)%3|0)|0]|0;Gd>c&&kg<0.7*Gd&&lc<0.7*Gd&&(e+=X,d+=lf,k=1+k|0);Fd=1+Fd|0;da=1+da|0}M=1+M|0;s=1+s|0}}f=1+f|0}return 1<k?pb(e/k,d/k):pb(-1E3,-1E3)}
function Va(a){var b=cb().createElement("canvas");b.width=(a.v.width|0)/a.M|0;b.height=(a.v.height|0)/a.M|0;H(I(),b).drawImage(a.Ca,0,0,b.width|0,b.height|0);return b}Ua.prototype.b=B({Nd:0},"arjs.GreenScreen",{Nd:1,c:1});function qb(){}qb.prototype=new C;qb.prototype.constructor=qb;qb.prototype.a=function(){return this};function H(a,b){return b.getContext("2d")}qb.prototype.b=B({Od:0},"arjs.package$",{Od:1,c:1});var rb=void 0;function I(){rb||(rb=(new qb).a());return rb}
function sb(){this.ci=this.Mc=this.md=this.$h=this.Zh=this.Yh=this.Xh=this.Wh=this.Rh=this.Qh=this.tc=this.Oh=this.Nh=this.Mh=this.Lh=this.Kh=this.Jh=this.Ih=this.Eh=this.Dh=this.Ch=this.Bh=this.Ah=this.zh=this.yh=this.xh=this.vh=this.uh=this.oh=null;this.Q=0}sb.prototype=new C;sb.prototype.constructor=sb;sb.prototype.a=function(){return this};
function cb(){var a;tb||(tb=(new sb).a());a=tb;0===(134217728&a.Q)&&0===(134217728&a.Q)&&(0===(67108864&a.Q)&&0===(67108864&a.Q)&&(a.md=t,a.Q|=67108864),a.Mc=a.md.document,a.Q|=134217728);return a.Mc}sb.prototype.b=B({Vd:0},"org.scalajs.dom.package$",{Vd:1,c:1});var tb=void 0;function Ia(){this.db=null}Ia.prototype=new C;Ia.prototype.constructor=Ia;function Ta(a){return a.db.name}Ia.prototype.k=function(){return(this.db.isInterface?"interface ":this.db.isPrimitive?"":"class ")+Ta(this)};
Ia.prototype.b=B({Se:0},"java.lang.Class",{Se:1,c:1});function ub(){}ub.prototype=new C;ub.prototype.constructor=ub;function vb(){}vb.prototype=ub.prototype;function wb(){this.Ae=this.Be=this.Nc=this.Zc=null}wb.prototype=new C;wb.prototype.constructor=wb;
wb.prototype.a=function(){xb=this;this.Zc=yb(!1);this.Nc=yb(!0);this.Be=null;this.Ae=t.performance?t.performance.now?function(){return+t.performance.now()}:t.performance.webkitNow?function(){return+t.performance.webkitNow()}:function(){return+(new t.Date).getTime()}:function(){return+(new t.Date).getTime()};return this};wb.prototype.b=B({bf:0},"java.lang.System$",{bf:1,c:1});var xb=void 0;function zb(){xb||(xb=(new wb).a());return xb}function Ab(){}Ab.prototype=new C;Ab.prototype.constructor=Ab;
function Bb(){}Bb.prototype=Ab.prototype;function Cb(){}Cb.prototype=new C;Cb.prototype.constructor=Cb;function Db(){}Db.prototype=Cb.prototype;function Eb(){}Eb.prototype=new C;Eb.prototype.constructor=Eb;Eb.prototype.a=function(){return this};Eb.prototype.b=B({Cf:0},"scala.math.Ordered$",{Cf:1,c:1});var Fb=void 0;
function Gb(){this.je=this.Pd=this.Dd=this.he=this.ge=this.de=this.Jd=this.Gd=this.Ed=this.th=this.sh=this.tc=this.oe=this.te=this.qd=this.ne=this.pd=this.sd=this.od=this.$d=this.Qd=this.Ld=this.Hd=this.ke=this.Kd=this.re=this.wd=null;this.Q=0}Gb.prototype=new C;Gb.prototype.constructor=Gb;
Gb.prototype.a=function(){Hb=this;this.wd=(new Ib).a();Jb||(Jb=(new Kb).a());this.re=Jb;Lb||(Lb=(new Mb).a());this.Kd=Lb;Nb||(Nb=(new Ob).a());this.ke=Nb;this.Hd=fb();this.Ld=Pb();this.Qd=Qb();this.$d=Rb();Sb||(Sb=(new Tb).a());this.od=Sb;Ub||(Ub=(new Vb).a());this.sd=Ub;Wb||(Wb=(new Xb).a());this.pd=Wb;Yb||(Yb=(new Zb).a());this.ne=Yb;$b||($b=(new ac).a());this.qd=$b;this.te=gb();bc||(bc=(new cc).a());this.oe=bc;this.tc=J();dc||(dc=(new ec).a());this.Ed=dc;fc||(fc=(new gc).a());this.Gd=fc;hc||(hc=
(new ic).a());this.Jd=hc;jc||(jc=(new kc).a());this.de=jc;Fb||(Fb=(new Eb).a());this.ge=Fb;mc||(mc=(new nc).a());this.he=mc;oc||(oc=(new pc).a());this.Dd=oc;qc||(qc=(new rc).a());this.Pd=qc;sc||(sc=(new tc).a());this.je=sc;return this};Gb.prototype.b=B({Ef:0},"scala.package$",{Ef:1,c:1});var Hb=void 0;function uc(){this.ce=this.be=this.xd=this.ee=this.vd=this.se=this.yd=this.Cd=this.Fd=this.Ud=this.Id=this.Ad=this.me=this.zd=null}uc.prototype=new C;uc.prototype.constructor=uc;
uc.prototype.a=function(){vc=this;wc||(wc=(new xc).a());this.zd=wc;yc||(yc=(new zc).a());this.me=yc;Ac||(Ac=(new Bc).a());this.Ad=Ac;Cc||(Cc=(new Dc).a());this.Id=Cc;Ec||(Ec=(new Fc).a());this.Ud=Ec;Gc||(Gc=(new Hc).a());this.Fd=Gc;Ic||(Ic=(new Jc).a());this.Cd=Ic;Kc||(Kc=(new Lc).a());this.yd=Kc;Mc||(Mc=(new Nc).a());this.se=Mc;Oc||(Oc=(new Pc).a());this.vd=Oc;Qc||(Qc=(new Rc).a());this.ee=Qc;Sc||(Sc=(new Tc).a());this.xd=Sc;Uc||(Uc=(new Vc).a());this.be=Uc;Wc||(Wc=(new Xc).a());this.ce=Wc;return this};
uc.prototype.b=B({Gf:0},"scala.reflect.ClassManifestFactory$",{Gf:1,c:1});var vc=void 0;function Yc(){}Yc.prototype=new C;Yc.prototype.constructor=Yc;Yc.prototype.a=function(){return this};Yc.prototype.b=B({Hf:0},"scala.reflect.ManifestFactory$",{Hf:1,c:1});var Zc=void 0;function $c(){this.pc=this.oc=null}$c.prototype=new C;$c.prototype.constructor=$c;$c.prototype.a=function(){ad=this;vc||(vc=(new uc).a());this.oc=vc;Zc||(Zc=(new Yc).a());this.pc=Zc;return this};
$c.prototype.b=B({Xf:0},"scala.reflect.package$",{Xf:1,c:1});var ad=void 0;function bd(){ad||(ad=(new $c).a());return ad}function P(){this.kc=null}P.prototype=new C;P.prototype.constructor=P;P.prototype.k=function(){return"DynamicVariable("+this.kc+")"};P.prototype.N=function(a){this.kc=a;return this};P.prototype.b=B({Yf:0},"scala.util.DynamicVariable",{Yf:1,c:1});function pc(){}pc.prototype=new C;pc.prototype.constructor=pc;pc.prototype.a=function(){return this};
pc.prototype.b=B({Zf:0},"scala.util.Either$",{Zf:1,c:1});var oc=void 0;function cd(){this.tg=null}cd.prototype=new C;cd.prototype.constructor=cd;cd.prototype.a=function(){this.tg=(new dd).a();return this};cd.prototype.b=B({dg:0},"scala.util.control.Breaks",{dg:1,c:1});function ed(){}ed.prototype=new C;ed.prototype.constructor=ed;function fd(){}fd.prototype=ed.prototype;function gd(a,b){var c;c=v(-862048943,b);c=v(461845907,c<<15|c>>>-15|0);c^=a;return-430675100+v(5,c<<13|c>>>-13|0)|0}
function hd(a){a=v(-2048144789,a^(a>>>16|0));a^=a>>>13|0;a=v(-1028477387,a);return a^=a>>>16|0}function id(a){jd();var b=a.xa();if(0===b)return a=a.za(),wa(A(),a);for(var c=-889275714,e=0;e<b;)c=gd(c,kd(ld(),a.ya(e))),e=1+e|0;return hd(c^b)}function md(a,b,c){var e=(new nd).o(0);c=(new nd).o(c);b.sa(od(function(a,b,c){return function(a){c.E=gd(c.E,kd(ld(),a));b.E=1+b.E|0}}(a,e,c)));return hd(c.E^e.E)}function Xb(){}Xb.prototype=new C;Xb.prototype.constructor=Xb;Xb.prototype.a=function(){return this};
Xb.prototype.b=B({gg:0},"scala.collection.$colon$plus$",{gg:1,c:1});var Wb=void 0;function Vb(){}Vb.prototype=new C;Vb.prototype.constructor=Vb;Vb.prototype.a=function(){return this};Vb.prototype.b=B({hg:0},"scala.collection.$plus$colon$",{hg:1,c:1});var Ub=void 0;function pd(a,b){for(var c=0,e=a.X();c<e;)b.P(a.qa(c)),c=1+c|0}function qd(){this.zb=null}qd.prototype=new C;qd.prototype.constructor=qd;qd.prototype.a=function(){rd=this;this.zb=(new sd).a();return this};
qd.prototype.b=B({ng:0},"scala.collection.Iterator$",{ng:1,c:1});var rd=void 0;function Pb(){rd||(rd=(new qd).a());return rd}function td(a,b,c,e,d){var k=ud();Q(b.I,c);a.sa(od(function(a,b,c,e){return function(a){if(b.E)vd(c,a),b.E=!1;else return Q(c.I,e),vd(c,a)}}(a,k,b,e)));Q(b.I,d);return b}function wd(){}wd.prototype=new C;wd.prototype.constructor=wd;function xd(){}xd.prototype=wd.prototype;function yd(){}yd.prototype=new C;yd.prototype.constructor=yd;function zd(){}zd.prototype=yd.prototype;
function ac(){}ac.prototype=new C;ac.prototype.constructor=ac;ac.prototype.a=function(){return this};ac.prototype.b=B({Ig:0},"scala.collection.immutable.Stream$$hash$colon$colon$",{Ig:1,c:1});var $b=void 0;
function Ad(a,b,c){if(32>c)return a.s().d[31&b];if(1024>c)return a.f().d[31&b>>5].d[31&b];if(32768>c)return a.h().d[31&b>>10].d[31&b>>5].d[31&b];if(1048576>c)return a.j().d[31&b>>15].d[31&b>>10].d[31&b>>5].d[31&b];if(33554432>c)return a.w().d[31&b>>20].d[31&b>>15].d[31&b>>10].d[31&b>>5].d[31&b];if(1073741824>c)return a.S().d[31&b>>25].d[31&b>>20].d[31&b>>15].d[31&b>>10].d[31&b>>5].d[31&b];throw(new O).a();}
function nb(a,b,c){a.aa(c);c=-1+c|0;switch(c){case -1:break;case 0:a.m(b.s());break;case 1:a.l(b.f());a.m(b.s());break;case 2:a.t(b.h());a.l(b.f());a.m(b.s());break;case 3:a.A(b.j());a.t(b.h());a.l(b.f());a.m(b.s());break;case 4:a.R(b.w());a.A(b.j());a.t(b.h());a.l(b.f());a.m(b.s());break;case 5:a.Na(b.S());a.R(b.w());a.A(b.j());a.t(b.h());a.l(b.f());a.m(b.s());break;default:throw(new L).N(c);}}
function ob(a,b,c){if(32<=c)if(1024>c)a.m(a.f().d[31&b>>5]);else if(32768>c)a.l(a.h().d[31&b>>10]),a.m(a.f().d[31&b>>5]);else if(1048576>c)a.t(a.j().d[31&b>>15]),a.l(a.h().d[31&b>>10]),a.m(a.f().d[31&b>>5]);else if(33554432>c)a.A(a.w().d[31&b>>20]),a.t(a.j().d[31&b>>15]),a.l(a.h().d[31&b>>10]),a.m(a.f().d[31&b>>5]);else if(1073741824>c)a.R(a.S().d[31&b>>25]),a.A(a.w().d[31&b>>20]),a.t(a.j().d[31&b>>15]),a.l(a.h().d[31&b>>10]),a.m(a.f().d[31&b>>5]);else throw(new O).a();}
function R(a){if(null===a){Bd||(Bd=(new Cd).a());for(var b=Bd.ad.kc,c="NULL\n";""!==c;){var e=c.indexOf("\n")|0;if(0>e)b.Ia=""+b.Ia+c,b.Db=!1,c="";else{var d=""+b.Ia+c.substring(0,e);t.console&&(b.Tc&&t.console.error?t.console.error(d):t.console.log(d));b.Ia="";b.Db=!0;c=c.substring(1+e|0)}}}b=x(E(D),[a.d.length]);c=a.d.length;a=a.d;e=b.d;if(a!==e||0>0+c)for(d=0;d<c;d++)e[0+d]=a[0+d];else for(d=c-1;0<=d;d--)e[0+d]=a[0+d];return b}
function Dd(){this.ka=!1;this.Pc=this.ze=this.jb=this.Fa=null;this.rb=!1;this.Xc=this.Sc=0}Dd.prototype=new C;Dd.prototype.constructor=Dd;
Dd.prototype.a=function(){Ed=this;this.Fa=(this.ka=!!(t.ArrayBuffer&&t.Int32Array&&t.Float32Array&&t.Float64Array))?new t.ArrayBuffer(8):null;this.jb=this.ka?new t.Int32Array(this.Fa,0,2):null;this.ze=this.ka?new t.Float32Array(this.Fa,0,2):null;this.Pc=this.ka?new t.Float64Array(this.Fa,0,1):null;if(this.ka)this.jb[0]=16909060,a=1===((new t.Int8Array(this.Fa,0,8))[0]|0);else var a=!0;this.Sc=(this.rb=a)?0:1;this.Xc=this.rb?1:0;return this};
function xa(a,b){var c=b|0;if(c===b&&-Infinity!==1/b)return c;if(a.ka)a.Pc[0]=b,c=Hd(Id((new K).o(a.jb[a.Sc]|0)),Jd((new K).n(-1,0),(new K).o(a.jb[a.Xc]|0)));else{if(b!==b)var c=!1,e=2047,d=+t.Math.pow(2,51);else if(Infinity===b||-Infinity===b)c=0>b,e=2047,d=0;else if(0===b)c=-Infinity===1/b,d=e=0;else{var k=(c=0>b)?-b:b;if(k>=+t.Math.pow(2,-1022)){var e=+t.Math.pow(2,52),d=+t.Math.log(k)/0.6931471805599453,d=+t.Math.floor(d)|0,d=1023>d?d:1023,n=k/+t.Math.pow(2,d)*e,k=+t.Math.floor(n),n=n-k,k=0.5>
n?k:0.5<n?1+k:0!==k%2?1+k:k;2<=k/e&&(d=1+d|0,k=1);1023<d?(d=2047,k=0):(d=1023+d|0,k-=e);e=d;d=k}else e=k/+t.Math.pow(2,-1074),d=+t.Math.floor(e),k=e-d,e=0,d=0.5>k?d:0.5<k?1+d:0!==d%2?1+d:d}d=+d;k=d|0;c=Hd(Id((new K).o((c?-2147483648:0)|(e|0)<<20|d/4294967296|0)),Jd((new K).n(-1,0),(new K).o(k)))}return c.i^c.u}Dd.prototype.b=B({bh:0},"scala.scalajs.runtime.Bits$",{bh:1,c:1});var Ed=void 0;function ya(){Ed||(Ed=(new Dd).a());return Ed}function Kd(){this.wh=null;this.Q=!1}Kd.prototype=new C;
Kd.prototype.constructor=Kd;Kd.prototype.a=function(){return this};function Ld(a,b,c){a=Md(c);return b.indexOf(a)|0}function Md(a){if(0===(-65536&a)){var b=t.String;return b.fromCharCode.apply(b,[a])}if(0>a||1114111<a)throw(new O).a();a=-65536+a|0;b=t.String;return b.fromCharCode.apply(b,[55296|a>>10,56320|1023&a])}function wa(a,b){for(var c=0,e=1,d=-1+(b.length|0)|0;0<=d;)c=c+v(65535&(b.charCodeAt(d)|0),e)|0,e=v(31,e),d=-1+d|0;return c}
Kd.prototype.b=B({dh:0},"scala.scalajs.runtime.RuntimeString$",{dh:1,c:1});var Nd=void 0;function A(){Nd||(Nd=(new Kd).a());return Nd}function Od(){}Od.prototype=new C;Od.prototype.constructor=Od;Od.prototype.a=function(){return this};function Pd(a,b){return b&&b.b&&b.b.L.ic?b.ra:b}function Qd(a,b){return b&&b.b&&b.b.L.W?b:(new Rd).N(b)}Od.prototype.b=B({eh:0},"scala.scalajs.runtime.package$",{eh:1,c:1});var Sd=void 0;function Td(){Sd||(Sd=(new Od).a());return Sd}
var sa=B({gh:0},"scala.runtime.BoxedUnit",{gh:1,c:1},void 0,void 0,function(a){return void 0===a});function Ud(){}Ud.prototype=new C;Ud.prototype.constructor=Ud;Ud.prototype.a=function(){return this};Ud.prototype.b=B({hh:0},"scala.runtime.BoxesRunTime$",{hh:1,c:1});var Vd=void 0,Wd=B({kh:0},"scala.runtime.Null$",{kh:1,c:1});function Xd(){}Xd.prototype=new C;Xd.prototype.constructor=Xd;Xd.prototype.a=function(){return this};
function kd(a,b){var c;if(null===b)c=0;else if(b&&b.b&&b.b.L.ia||"number"===typeof b)if(Vd||(Vd=(new Ud).a()),(b|0)===b&&1/b!==1/-0)c=b|0;else if(ta(b)){c=(null===b?Ha().ha:b).i;var e=(new K).o(c),d=null===b?Ha().ha:b;if(e.i!==d.i||e.u!==d.u)c=null===b?Ha().ha:b,c=c.i^c.u}else if("number"===typeof b)if(e=Aa(+b),c=+b,e===c)c=e;else{var e=Yd(Ha(),+b),d=e.i,k=e.u;c=(0>k?-(4294967296*+((0!==d?~k:-k|0)>>>0)+ +((-d|0)>>>0)):4294967296*k+ +(d>>>0))===c?e.i^e.u:xa(ya(),+b)}else c=va(b);else c=va(b);return c}
Xd.prototype.b=B({lh:0},"scala.runtime.ScalaRunTime$",{lh:1,c:1});var Zd=void 0;function ld(){Zd||(Zd=(new Xd).a());return Zd}var ra=B({Pe:0},"java.lang.Boolean",{Pe:1,c:1,T:1},void 0,void 0,function(a){return"boolean"===typeof a});function $d(){this.lc=0}$d.prototype=new C;$d.prototype.constructor=$d;$d.prototype.k=function(){return t.String.fromCharCode(this.lc)};function ae(a){var b=new $d;b.lc=a;return b}$d.prototype.B=h("lc");$d.prototype.b=B({Re:0},"java.lang.Character",{Re:1,c:1,T:1});
function S(){this.Vi=this.we=this.bd=null}S.prototype=new C;S.prototype.constructor=S;function be(){}be.prototype=S.prototype;S.prototype.gb=function(){if(void 0===t.Error.captureStackTrace){try{var a={}.undef()}catch(b){if(a=Qd(Td(),b),null!==a)if(a&&a.b&&a.b.L.ic)a=a.ra;else throw Pd(Td(),a);else throw b;}this.stackdata=a}else t.Error.captureStackTrace(this),this.stackdata=this;return this};S.prototype.Qc=h("bd");S.prototype.k=function(){var a=Ta(ka(this)),b=this.Qc();return null===b?a:a+": "+b};
S.prototype.V=function(a,b){this.bd=a;this.we=b;this.gb();return this};function ce(){this.fi=this.fc=this.ec=0;this.Rc=!1}ce.prototype=new C;ce.prototype.constructor=ce;ce.prototype.a=function(){ce.prototype.Fe.call(this,de());return this};ce.prototype.Fe=function(a){this.Rc=!1;var b=(new K).n(-554899859,5);a=Jd((new K).n(-1,65535),(new K).n(b.i^a.i,b.u^a.u));b=a.u;this.ec=(new K).n(a.i>>>24|0|b<<-24,b>>>24|0).i;this.fc=16777215&a.i;this.Rc=!1;return this};
function bb(a,b){if(0>=b)throw(new O).p("n must be positive");var c;if((b&(-b|0))===b)c=ee(a)>>ca(b);else a:{for(;;){c=ee(a);var e=c%b|0;if(!(0>((c-e|0)+(-1+b|0)|0))){c=e;break a}}c=void 0}return c}function ee(a){var b=a.fc,c=11+15525485*b,b=16777215&((c/16777216|0)+(16777215&(1502*b+15525485*a.ec|0))|0),c=16777215&(c|0);a.ec=b;a.fc=c;return(b<<8|c>>16)>>>1|0}ce.prototype.b=B({ef:0},"java.util.Random",{ef:1,c:1,e:1});function fe(){}fe.prototype=new C;fe.prototype.constructor=fe;fe.prototype.a=function(){return this};
fe.prototype.b=B({tf:0},"scala.Predef$$anon$3",{tf:1,c:1,ed:1});function Ib(){}Ib.prototype=new C;Ib.prototype.constructor=Ib;Ib.prototype.a=function(){return this};Ib.prototype.k=m("object AnyRef");Ib.prototype.b=B({Ff:0},"scala.package$$anon$1",{Ff:1,c:1,pi:1});function ge(){this.Yg=this.hf=this.hc=this.Yi=this.Xi=this.gi=this.Wi=this.ai=0}ge.prototype=new fd;ge.prototype.constructor=ge;ge.prototype.a=function(){he=this;this.hc=wa(A(),"Seq");this.hf=wa(A(),"Map");this.Yg=wa(A(),"Set");return this};
function ie(a){var b=jd();return a&&a.b&&a.b.L.zg?hd(b.hc^0):md(b,a,b.hc)}ge.prototype.b=B({fg:0},"scala.util.hashing.MurmurHash3$",{fg:1,xi:1,c:1});var he=void 0;function jd(){he||(he=(new ge).a());return he}function je(){}je.prototype=new zd;je.prototype.constructor=je;function ke(){}ke.prototype=je.prototype;function T(){this.J=null}T.prototype=new zd;T.prototype.constructor=T;function le(){}le.prototype=T.prototype;T.prototype.a=function(){this.J=(new me).ib(this);return this};
function ne(){this.na=null}ne.prototype=new C;ne.prototype.constructor=ne;function oe(){}oe.prototype=ne.prototype;ne.prototype.ib=function(a){if(null===a)throw Pd(Td(),null);this.na=a;return this};function pe(){}pe.prototype=new xd;pe.prototype.constructor=pe;function qe(){}qe.prototype=pe.prototype;function re(){}re.prototype=new C;re.prototype.constructor=re;re.prototype.a=function(){return this};re.prototype.P=function(){return this};re.prototype.k=m("\x3cfunction1\x3e");
re.prototype.b=B({Bg:0},"scala.collection.immutable.List$$anon$1",{Bg:1,c:1,ga:1});function se(){}se.prototype=new C;se.prototype.constructor=se;function te(){}te.prototype=se.prototype;se.prototype.k=m("\x3cfunction1\x3e");function ue(){this.E=!1}ue.prototype=new C;ue.prototype.constructor=ue;ue.prototype.k=function(){return""+this.E};function ud(){var a=new ue;a.E=!0;return a}ue.prototype.b=B({fh:0},"scala.runtime.BooleanRef",{fh:1,c:1,e:1});function nd(){this.E=0}nd.prototype=new C;
nd.prototype.constructor=nd;nd.prototype.k=function(){return""+this.E};nd.prototype.o=function(a){this.E=a;return this};nd.prototype.b=B({ih:0},"scala.runtime.IntRef",{ih:1,c:1,e:1});function ve(){}ve.prototype=new C;ve.prototype.constructor=ve;function we(){}we.prototype=ve.prototype;var ma=B({Qe:0},"java.lang.Byte",{Qe:1,ia:1,c:1,T:1},void 0,void 0,function(a){return a<<24>>24===a&&1/a!==1/-0}),qa=B({Te:0},"java.lang.Double",{Te:1,ia:1,c:1,T:1},void 0,void 0,function(a){return"number"===typeof a});
function xe(){S.call(this)}xe.prototype=new be;xe.prototype.constructor=xe;function ye(){}ye.prototype=xe.prototype;
var pa=B({Ue:0},"java.lang.Float",{Ue:1,ia:1,c:1,T:1},void 0,void 0,function(a){return"number"===typeof a}),oa=B({We:0},"java.lang.Integer",{We:1,ia:1,c:1,T:1},void 0,void 0,function(a){return(a|0)===a&&1/a!==1/-0}),ua=B({Ze:0},"java.lang.Long",{Ze:1,ia:1,c:1,T:1},void 0,void 0,function(a){return ta(a)}),na=B({$e:0},"java.lang.Short",{$e:1,ia:1,c:1,T:1},void 0,void 0,function(a){return a<<16>>16===a&&1/a!==1/-0});function ze(){}ze.prototype=new C;ze.prototype.constructor=ze;ze.prototype.a=function(){return this};
function de(){Ae||(Ae=(new ze).a());return Hd(Id((new K).o(Be())),Jd((new K).n(-1,0),(new K).o(Be())))}function Be(){var a=4294967296*+t.Math.random();return Aa(-2147483648+ +t.Math.floor(a))}ze.prototype.b=B({ff:0},"java.util.Random$",{ff:1,c:1,g:1,e:1});var Ae=void 0;function Cd(){this.Ce=this.xe=this.ad=null}Cd.prototype=new Bb;Cd.prototype.constructor=Cd;Cd.prototype.a=function(){Bd=this;this.ad=(new P).N(zb().Zc);this.xe=(new P).N(zb().Nc);this.Ce=(new P).N(null);return this};
Cd.prototype.b=B({lf:0},"scala.Console$",{lf:1,hi:1,c:1,qi:1});var Bd=void 0;function Ce(){this.sg=this.Zg=this.pe=this.ae=this.Xd=this.Bd=this.le=this.Yd=null}Ce.prototype=new Db;Ce.prototype.constructor=Ce;Ce.prototype.a=function(){De=this;Hb||(Hb=(new Gb).a());Qb();Ee||(Ee=(new Fe).a());this.Yd=Ee;Ge||(Ge=(new He).a());this.le=Ge;this.Bd=bd().oc;this.Xd=bd().pc;Ie||(Ie=(new Je).a());this.ae=Ie;this.pe=(new fe).a();this.Zg=(new Ke).a();this.sg=(new Le).a();return this};
Ce.prototype.b=B({qf:0},"scala.Predef$",{qf:1,ji:1,c:1,ii:1});var De=void 0;function Me(){}Me.prototype=new C;Me.prototype.constructor=Me;Me.prototype.a=function(){return this};Me.prototype.b=B({vf:0},"scala.StringContext$",{vf:1,c:1,g:1,e:1});var Ne=void 0;function gc(){}gc.prototype=new C;gc.prototype.constructor=gc;gc.prototype.a=function(){return this};gc.prototype.b=B({zf:0},"scala.math.Fractional$",{zf:1,c:1,g:1,e:1});var fc=void 0;function ic(){}ic.prototype=new C;
ic.prototype.constructor=ic;ic.prototype.a=function(){return this};ic.prototype.b=B({Af:0},"scala.math.Integral$",{Af:1,c:1,g:1,e:1});var hc=void 0;function kc(){}kc.prototype=new C;kc.prototype.constructor=kc;kc.prototype.a=function(){return this};kc.prototype.b=B({Bf:0},"scala.math.Numeric$",{Bf:1,c:1,g:1,e:1});var jc=void 0;function rc(){}rc.prototype=new C;rc.prototype.constructor=rc;rc.prototype.a=function(){return this};rc.prototype.k=m("Left");
rc.prototype.b=B({$f:0},"scala.util.Left$",{$f:1,c:1,g:1,e:1});var qc=void 0;function Oe(){this.gc=null}Oe.prototype=new C;Oe.prototype.constructor=Oe;function Pe(){}Pe.prototype=Oe.prototype;Oe.prototype.Ke=function(a){this.gc=a;return this};function tc(){}tc.prototype=new C;tc.prototype.constructor=tc;tc.prototype.a=function(){return this};tc.prototype.k=m("Right");tc.prototype.b=B({bg:0},"scala.util.Right$",{bg:1,c:1,g:1,e:1});var sc=void 0;function Qe(){this.nc=!1}Qe.prototype=new C;
Qe.prototype.constructor=Qe;Qe.prototype.a=function(){this.nc=!1;return this};Qe.prototype.b=B({eg:0},"scala.util.control.NoStackTrace$",{eg:1,c:1,g:1,e:1});var Re=void 0;function Se(){this.na=null}Se.prototype=new oe;Se.prototype.constructor=Se;Se.prototype.a=function(){ne.prototype.ib.call(this,fb());return this};Se.prototype.b=B({jg:0},"scala.collection.IndexedSeq$$anon$1",{jg:1,vg:1,c:1,ed:1});function Te(){this.J=null}Te.prototype=new le;Te.prototype.constructor=Te;function Ue(){}
Ue.prototype=Te.prototype;function me(){this.rd=this.na=null}me.prototype=new oe;me.prototype.constructor=me;me.prototype.ib=function(a){if(null===a)throw Pd(Td(),null);this.rd=a;ne.prototype.ib.call(this,a);return this};me.prototype.b=B({ug:0},"scala.collection.generic.GenTraversableFactory$$anon$1",{ug:1,vg:1,c:1,ed:1});function Ve(){}Ve.prototype=new qe;Ve.prototype.constructor=Ve;function We(){}We.prototype=Ve.prototype;function Tb(){}Tb.prototype=new C;Tb.prototype.constructor=Tb;
Tb.prototype.a=function(){return this};Tb.prototype.k=m("::");Tb.prototype.b=B({wg:0},"scala.collection.immutable.$colon$colon$",{wg:1,c:1,g:1,e:1});var Sb=void 0;function Xe(){this.Wd=0}Xe.prototype=new C;Xe.prototype.constructor=Xe;Xe.prototype.a=function(){this.Wd=512;return this};function Wa(a,b,c,e){throw(new O).p(b+" until "+c+" by "+e+": seqs cannot contain more than Int.MaxValue elements.");}Xe.prototype.b=B({Eg:0},"scala.collection.immutable.Range$",{Eg:1,c:1,g:1,e:1});var Ye=void 0;
function J(){Ye||(Ye=(new Xe).a());return Ye}function cc(){}cc.prototype=new C;cc.prototype.constructor=cc;cc.prototype.a=function(){return this};cc.prototype.b=B({Wg:0},"scala.collection.mutable.StringBuilder$",{Wg:1,c:1,g:1,e:1});var bc=void 0;function Ze(){this.Oc=null}Ze.prototype=new te;Ze.prototype.constructor=Ze;Ze.prototype.P=function(a){return(0,this.Oc)(a)};function od(a){var b=new Ze;b.Oc=a;return b}Ze.prototype.b=B({ah:0},"scala.scalajs.runtime.AnonFunction1",{ah:1,Ui:1,c:1,ga:1});
function $e(){this.ph=this.rh=this.qh=this.Vh=this.Uh=this.Th=0;this.qc=this.rc=this.Zd=this.fe=this.ha=null}$e.prototype=new C;$e.prototype.constructor=$e;$e.prototype.a=function(){af=this;this.ha=(new K).n(0,0);this.fe=(new K).n(1,0);this.Zd=(new K).n(-1,-1);this.rc=(new K).n(0,-2147483648);this.qc=(new K).n(-1,2147483647);return this};
function Yd(a,b){if(b!==b)return a.ha;if(-9223372036854775E3>b)return a.rc;if(9223372036854775E3<=b)return a.qc;var c=0>b,e=c?-b:b,d=e|0,e=e/4294967296|0;return c?(new K).n(-d|0,0!==d?~e:-e|0):(new K).n(d,e)}$e.prototype.b=B({ch:0},"scala.scalajs.runtime.RuntimeLong$",{ch:1,c:1,g:1,e:1});var af=void 0;function Ha(){af||(af=(new $e).a());return af}var bf=B({jh:0},"scala.runtime.Nothing$",{jh:1,W:1,c:1,e:1});function cf(){this.$c=null}cf.prototype=new we;cf.prototype.constructor=cf;function df(){}
df.prototype=cf.prototype;cf.prototype.Ge=function(a){this.$c=a;return this};var la=B({qe:0},"java.lang.String",{qe:1,c:1,e:1,Uc:1,T:1},void 0,void 0,function(a){return"string"===typeof a});function ef(){}ef.prototype=new we;ef.prototype.constructor=ef;ef.prototype.a=function(){return this};ef.prototype.b=B({Ye:0},"java.lang.JSConsoleBasedPrintStream$DummyOutputStream",{Ye:1,Td:1,c:1,Rd:1,Sd:1});function ff(){S.call(this)}ff.prototype=new ye;ff.prototype.constructor=ff;function gf(){}
gf.prototype=ff.prototype;function U(){this.z=null}U.prototype=new C;U.prototype.constructor=U;p=U.prototype;p.a=function(){U.prototype.p.call(this,"");return this};function Q(a,b){a.z=""+a.z+(null===b?"null":b);return a}p.ld=function(a,b){return this.z.substring(a,b)};p.k=h("z");function hf(a,b){null===b?Q(a,null):Q(a,ja(b))}p.o=function(){U.prototype.p.call(this,"");return this};function jf(a,b,c,e){return null===b?jf(a,"null",c,e):Q(a,ja("string"===typeof b?b.substring(c,e):b.ld(c,e)))}
p.p=function(a){this.z=a;return this};p.b=B({af:0},"java.lang.StringBuilder",{af:1,c:1,Uc:1,Oe:1,e:1});function kf(){}kf.prototype=new C;kf.prototype.constructor=kf;function mf(){}mf.prototype=kf.prototype;kf.prototype.k=m("\x3cfunction1\x3e");function nf(){}nf.prototype=new C;nf.prototype.constructor=nf;function of(){}of.prototype=nf.prototype;nf.prototype.k=m("\x3cfunction1\x3e");function ec(){}ec.prototype=new C;ec.prototype.constructor=ec;ec.prototype.a=function(){return this};
ec.prototype.b=B({yf:0},"scala.math.Equiv$",{yf:1,c:1,ri:1,g:1,e:1});var dc=void 0;function nc(){}nc.prototype=new C;nc.prototype.constructor=nc;nc.prototype.a=function(){return this};nc.prototype.b=B({Df:0},"scala.math.Ordering$",{Df:1,c:1,si:1,g:1,e:1});var mc=void 0;function Je(){}Je.prototype=new C;Je.prototype.constructor=Je;Je.prototype.a=function(){return this};Je.prototype.k=m("\x3c?\x3e");Je.prototype.b=B({Wf:0},"scala.reflect.NoManifest$",{Wf:1,c:1,C:1,g:1,e:1});var Ie=void 0;
function ab(){this.gc=null}ab.prototype=new Pe;ab.prototype.constructor=ab;ab.prototype.a=function(){Oe.prototype.Ke.call(this,(new ce).a());return this};ab.prototype.b=B({ag:0},"scala.util.Random$",{ag:1,ui:1,c:1,g:1,e:1});var $a=void 0;function pf(){}pf.prototype=new C;pf.prototype.constructor=pf;function qf(){}qf.prototype=pf.prototype;pf.prototype.k=function(){return(this.U()?"non-empty":"empty")+" iterator"};pf.prototype.sa=function(a){for(;this.U();)a.P(this.O())};
pf.prototype.qb=function(a,b,c,e){return td(this,a,b,c,e)};function rf(){}rf.prototype=new ke;rf.prototype.constructor=rf;function sf(){}sf.prototype=rf.prototype;function Fe(){}Fe.prototype=new We;Fe.prototype.constructor=Fe;Fe.prototype.a=function(){return this};Fe.prototype.b=B({Cg:0},"scala.collection.immutable.Map$",{Cg:1,Gi:1,Ii:1,Ei:1,c:1});var Ee=void 0;function K(){this.u=this.i=0}K.prototype=new vb;K.prototype.constructor=K;function Hd(a,b){return(new K).n(a.i|b.i,a.u|b.u)}p=K.prototype;
p.Eb=function(a,b,c){K.prototype.n.call(this,a|b<<22,b>>10|c<<12);return this};p.k=function(){var a=this.i,b=this.u;return b===a>>31?""+a:0>b?"-"+tf(-a|0,0!==a?~b:-b|0):tf(a,b)};p.n=function(a,b){this.i=a;this.u=b;return this};function Jd(a,b){return(new K).n(a.i&b.i,a.u&b.u)}function Xa(a){var b=(new K).n(2147483647,0),c=a.u,e=b.u;return c===e?(-2147483648^b.i)<(-2147483648^a.i):e<c}function Id(a){return(new K).n(0,a.i<<32)}p.o=function(a){K.prototype.n.call(this,a,a>>31);return this};
p.B=function(){return this.i^this.u};
function tf(a,b){if(0===(-2097152&b))return""+(4294967296*b+ +(a>>>0));var c,e=(32+ca(1E9)|0)-(0!==b?ca(b):32+ca(a)|0)|0,d=e;0===d?(c=1E9,d=0):32>d?(c=1E9<<d,d=1E9>>>(-d|0)|0|0<<d):(c=0,d=1E9<<d);for(var k=c,n=d,f=a,l=b,d=c=0;0<=e&&0!==(-2097152&l);){var u=f,q=l,s=k,y=n;if(q===y?(-2147483648^u)>=(-2147483648^s):(-2147483648^q)>=(-2147483648^y))u=f,f=u-k|0,l=(l-n|0)+((-2147483648^u)<(-2147483648^f)?-1:0)|0,32>e?c|=1<<e:d|=1<<e;e=-1+e|0;u=n>>>1|0;k=k>>>1|0|n<<-1;n=u}e=l;if(0===e?-1147483648<=(-2147483648^
f):-2147483648<=(-2147483648^e))e=4294967296*l+ +(f>>>0),k=e/1E9,f=c,c=l=f+(k|0)|0,d=(d+(k/4294967296|0)|0)+((-2147483648^l)<(-2147483648^f)?1:0)|0,e%=1E9,f=e|0,l=e/4294967296|0;c=[c,d,f,l];d=""+(c["2"]|0);return""+(4294967296*(c["1"]|0)+ +((c["0"]|0)>>>0))+"000000000".substring(d.length|0)+d}function Ya(a,b){var c=a.i,e=c-b.i|0;return(new K).n(e,(a.u-b.u|0)+((-2147483648^c)<(-2147483648^e)?-1:0)|0)}function ta(a){return!!(a&&a.b&&a.b.L.kd)}
p.b=B({kd:0},"scala.scalajs.runtime.RuntimeLong",{kd:1,ia:1,c:1,e:1,T:1});function O(){S.call(this)}O.prototype=new gf;O.prototype.constructor=O;function uf(){}uf.prototype=O.prototype;O.prototype.a=function(){S.prototype.V.call(this,null,null);return this};O.prototype.p=function(a){S.prototype.V.call(this,a,null);return this};O.prototype.b=B({Wc:0},"java.lang.IllegalArgumentException",{Wc:1,wa:1,va:1,W:1,c:1,e:1});function V(){S.call(this)}V.prototype=new gf;V.prototype.constructor=V;
V.prototype.p=function(a){S.prototype.V.call(this,a,null);return this};V.prototype.b=B({Ve:0},"java.lang.IndexOutOfBoundsException",{Ve:1,wa:1,va:1,W:1,c:1,e:1});function vf(){S.call(this)}vf.prototype=new gf;vf.prototype.constructor=vf;vf.prototype.p=function(a){S.prototype.V.call(this,a,null);return this};vf.prototype.b=B({cf:0},"java.lang.UnsupportedOperationException",{cf:1,wa:1,va:1,W:1,c:1,e:1});function wf(){S.call(this)}wf.prototype=new gf;wf.prototype.constructor=wf;
wf.prototype.p=function(a){S.prototype.V.call(this,a,null);return this};wf.prototype.b=B({df:0},"java.util.NoSuchElementException",{df:1,wa:1,va:1,W:1,c:1,e:1});function L(){S.call(this);this.Yc=this.Ra=null;this.sb=!1}L.prototype=new gf;L.prototype.constructor=L;
L.prototype.Qc=function(){if(!this.sb&&!this.sb){var a;if(null===this.Ra)a="null";else try{a=ja(this.Ra)+" ("+("of class "+Ta(ka(this.Ra)))+")"}catch(b){if(null!==Qd(Td(),b))a="an instance of class "+Ta(ka(this.Ra));else throw b;}this.Yc=a;this.sb=!0}return this.Yc};L.prototype.N=function(a){this.Ra=a;S.prototype.V.call(this,null,null);return this};L.prototype.b=B({nf:0},"scala.MatchError",{nf:1,wa:1,va:1,W:1,c:1,e:1});function xf(){}xf.prototype=new C;xf.prototype.constructor=xf;function yf(){}
yf.prototype=xf.prototype;function Ke(){}Ke.prototype=new of;Ke.prototype.constructor=Ke;Ke.prototype.a=function(){return this};Ke.prototype.P=function(a){return a};Ke.prototype.b=B({rf:0},"scala.Predef$$anon$1",{rf:1,mi:1,c:1,ga:1,g:1,e:1});function Le(){}Le.prototype=new mf;Le.prototype.constructor=Le;Le.prototype.a=function(){return this};Le.prototype.P=function(a){return a};Le.prototype.b=B({sf:0},"scala.Predef$$anon$2",{sf:1,li:1,c:1,ga:1,g:1,e:1});function kb(){this.Sa=null}kb.prototype=new C;
kb.prototype.constructor=kb;p=kb.prototype;p.za=m("StringContext");p.xa=m(1);p.ya=function(a){switch(a){case 0:return this.Sa;default:throw(new V).p(""+a);}};p.k=function(){ld();return this.Ua().qb((new zf).a(),this.za()+"(",",",")").I.z};function Af(a,b){if(a.Sa.X()!==(1+b.X()|0))throw(new O).p("wrong number of arguments ("+b.X()+") for interpolated string with "+a.Sa.X()+" parts");}
function ib(a,b){var c=function(){return function(a){Ne||(Ne=(new Me).a());a:{var b=a.length|0,c=Ld(A(),a,92);switch(c){case -1:break a;default:var e=(new U).a();b:{var d=c,c=0;for(;;)if(0<=d){d>c&&jf(e,a,c,d);c=1+d|0;if(c>=b)throw Bf(a,d);var k=65535&(a.charCodeAt(c)|0);switch(k){case 98:d=8;break;case 116:d=9;break;case 110:d=10;break;case 102:d=12;break;case 114:d=13;break;case 34:d=34;break;case 39:d=39;break;case 92:d=92;break;default:if(48<=k&&55>=k){k=65535&(a.charCodeAt(c)|0);d=-48+k|0;c=
1+c|0;if(c<b&&48<=(65535&(a.charCodeAt(c)|0))&&55>=(65535&(a.charCodeAt(c)|0))){var n=c,d=-48+(v(8,d)+(65535&(a.charCodeAt(n)|0))|0)|0,c=1+c|0;c<b&&51>=k&&48<=(65535&(a.charCodeAt(c)|0))&&55>=(65535&(a.charCodeAt(c)|0))&&(k=c,d=-48+(v(8,d)+(65535&(a.charCodeAt(k)|0))|0)|0,c=1+c|0)}c=-1+c|0;d&=65535}else throw Bf(a,d);}c=1+c|0;Q(e,t.String.fromCharCode(d));d=c;A();k=a;n=Md(92);k=k.indexOf(n,c)|0;c=d;d=k}else{c<b&&jf(e,a,c,b);a=e.z;break b}a=void 0}}}return a}}(a);Af(a,b);for(var e=a.Sa.ua(),d=b.ua(),
k=e.O(),k=(new U).p(c(k));d.U();){hf(k,d.O());var n=e.O();Q(k,c(n))}return k.z}function jb(a,b){a.Sa=b;return a}p.B=function(){return id(this)};p.Ua=function(){return Cf(this)};p.b=B({uf:0},"scala.StringContext",{uf:1,c:1,lb:1,r:1,g:1,e:1});function dd(){S.call(this)}dd.prototype=new be;dd.prototype.constructor=dd;dd.prototype.a=function(){S.prototype.V.call(this,null,null);return this};dd.prototype.gb=function(){Re||(Re=(new Qe).a());return Re.nc?S.prototype.gb.call(this):this};
dd.prototype.b=B({cg:0},"scala.util.control.BreakControl",{cg:1,W:1,c:1,e:1,vi:1,wi:1});function Mb(){this.J=null}Mb.prototype=new le;Mb.prototype.constructor=Mb;Mb.prototype.a=function(){T.prototype.a.call(this);return this};Mb.prototype.b=B({mg:0},"scala.collection.Iterable$",{mg:1,la:1,ea:1,c:1,ma:1,fa:1});var Lb=void 0;function sd(){}sd.prototype=new qf;sd.prototype.constructor=sd;sd.prototype.a=function(){return this};sd.prototype.O=function(){throw(new wf).p("next on empty iterator");};
sd.prototype.U=m(!1);sd.prototype.b=B({og:0},"scala.collection.Iterator$$anon$2",{og:1,ob:1,c:1,pb:1,da:1,ca:1});function Df(){this.nh=null}Df.prototype=new qf;Df.prototype.constructor=Df;Df.prototype.O=function(){if(this.U()){throw(new wf).p("head of empty list");throw(new vf).p("tail of empty list");}return Pb().zb.O()};Df.prototype.U=m(!1);Df.prototype.b=B({pg:0},"scala.collection.LinearSeqLike$$anon$1",{pg:1,ob:1,c:1,pb:1,da:1,ca:1});function Kb(){this.ue=this.J=null}Kb.prototype=new le;
Kb.prototype.constructor=Kb;Kb.prototype.a=function(){T.prototype.a.call(this);Jb=this;this.ue=(new cd).a();return this};Kb.prototype.b=B({rg:0},"scala.collection.Traversable$",{rg:1,la:1,ea:1,c:1,ma:1,fa:1});var Jb=void 0;function Ef(){}Ef.prototype=new sf;Ef.prototype.constructor=Ef;function Ff(){}Ff.prototype=Ef.prototype;function hb(){this.La=this.ja=this.Ha=0;this.Jc=this.Gc=this.Dc=this.Ac=this.xc=this.Ma=null}hb.prototype=new C;hb.prototype.constructor=hb;p=hb.prototype;p.j=h("Dc");
p.a=function(){this.Ma=x(E(D),[32]);this.La=1;this.ja=this.Ha=0;return this};p.D=h("La");p.Na=g("Jc");p.s=h("Ma");p.w=h("Gc");p.t=g("Ac");p.l=g("xc");p.R=g("Gc");p.f=h("xc");p.S=h("Jc");p.aa=g("La");p.h=h("Ac");p.m=g("Ma");p.A=g("Dc");p.b=B({Mg:0},"scala.collection.immutable.VectorBuilder",{Mg:1,c:1,jd:1,gd:1,fd:1,id:1});function Gf(){this.uc=this.Ja=0;this.nd=null}Gf.prototype=new qf;Gf.prototype.constructor=Gf;Gf.prototype.O=function(){var a=this.nd.ya(this.Ja);this.Ja=1+this.Ja|0;return a};
function Cf(a){var b=new Gf;b.nd=a;b.Ja=0;b.uc=a.xa();return b}Gf.prototype.U=function(){return this.Ja<this.uc};Gf.prototype.b=B({mh:0},"scala.runtime.ScalaRunTime$$anon$1",{mh:1,ob:1,c:1,pb:1,da:1,ca:1});function Hf(){this.$c=null;this.Le=!1;this.ei=this.ve=null;this.bi=this.ye=this.Me=this.Ne=!1}Hf.prototype=new df;Hf.prototype.constructor=Hf;function If(){}If.prototype=Hf.prototype;Hf.prototype.He=function(a,b,c){this.Le=b;this.ve=c;cf.prototype.Ge.call(this,a);this.ye=this.Me=this.Ne=!1;return this};
function Jf(){this.ud=this.td=null}Jf.prototype=new C;Jf.prototype.constructor=Jf;function Kf(){}p=Kf.prototype=Jf.prototype;p.za=m("Tuple2");p.xa=m(2);p.ya=function(a){a:switch(a){case 0:a=this.oa;break a;case 1:a=this.pa;break a;default:throw(new V).p(""+a);}return a};p.Ie=function(a,b){this.td=a;this.ud=b;return this};p.k=function(){return"("+this.oa+","+this.pa+")"};p.B=function(){return id(this)};p.Ua=function(){return Cf(this)};function Lf(){}Lf.prototype=new yf;Lf.prototype.constructor=Lf;
p=Lf.prototype;p.a=function(){return this};p.za=m("None");p.xa=m(0);p.ya=function(a){throw(new V).p(""+a);};p.k=m("None");p.B=m(2433880);p.Ua=function(){return Cf(this)};p.b=B({pf:0},"scala.None$",{pf:1,ki:1,c:1,lb:1,r:1,g:1,e:1});var Mf=void 0;function Nf(){Mf||(Mf=(new Lf).a());return Mf}function Of(){S.call(this);this.De=0}Of.prototype=new uf;Of.prototype.constructor=Of;
function Bf(a,b){var c=new Of;c.De=b;var e=jb(new kb,lb(new N,["invalid escape "," index ",' in "','". Use \\\\\\\\ for literal \\\\.']));De||(De=(new Ce).a());if(!(0<=b&&b<(a.length|0)))throw(new O).p("requirement failed");if(b===(-1+(a.length|0)|0))var d="at terminal";else var d=jb(new kb,lb(new N,["'\\\\","' not one of "," at"])),k=65535&(a.charCodeAt(1+b|0)|0),d=ib(d,lb(new N,[ae(k),"[\\b, \\t, \\n, \\f, \\r, \\\\, \\\", \\']"]));e=ib(e,lb(new N,[d,b,a]));S.prototype.V.call(c,e,null);return c}
Of.prototype.b=B({wf:0},"scala.StringContext$InvalidEscapeException",{wf:1,Wc:1,wa:1,va:1,W:1,c:1,e:1});function Pf(){this.J=null}Pf.prototype=new Ue;Pf.prototype.constructor=Pf;function Qf(){}Qf.prototype=Pf.prototype;function He(){}He.prototype=new Ff;He.prototype.constructor=He;He.prototype.a=function(){return this};He.prototype.b=B({Gg:0},"scala.collection.immutable.Set$",{Gg:1,Hi:1,Ji:1,Fi:1,ea:1,c:1,fa:1});var Ge=void 0;
function Rf(){this.Cb=this.i=this.$=this.Bb=0;this.Za=!1;this.wb=0;this.Kc=this.Hc=this.Ec=this.Bc=this.yc=this.yb=null}Rf.prototype=new qf;Rf.prototype.constructor=Rf;p=Rf.prototype;
p.O=function(){if(!this.Za)throw(new wf).p("reached iterator end");var a=this.yb.d[this.i];this.i=1+this.i|0;if(this.i===this.Cb)if((this.$+this.i|0)<this.Bb){var b=32+this.$|0,c=this.$^b;if(1024>c)this.m(this.f().d[31&b>>5]);else if(32768>c)this.l(this.h().d[31&b>>10]),this.m(this.f().d[0]);else if(1048576>c)this.t(this.j().d[31&b>>15]),this.l(this.h().d[0]),this.m(this.f().d[0]);else if(33554432>c)this.A(this.w().d[31&b>>20]),this.t(this.j().d[0]),this.l(this.h().d[0]),this.m(this.f().d[0]);else if(1073741824>
c)this.R(this.S().d[31&b>>25]),this.A(this.w().d[0]),this.t(this.j().d[0]),this.l(this.h().d[0]),this.m(this.f().d[0]);else throw(new O).a();this.$=b;b=this.Bb-this.$|0;this.Cb=32>b?b:32;this.i=0}else this.Za=!1;return a};p.j=h("Ec");p.D=h("wb");p.Na=g("Kc");p.n=function(a,b){this.Bb=b;this.$=-32&a;this.i=31&a;var c=b-this.$|0;this.Cb=32>c?c:32;this.Za=(this.$+this.i|0)<b;return this};p.s=h("yb");p.w=h("Hc");p.t=g("Bc");p.l=g("yc");p.U=h("Za");p.R=g("Hc");p.f=h("yc");p.S=h("Kc");p.aa=g("wb");
p.h=h("Bc");p.m=g("yb");p.A=g("Ec");p.b=B({Ng:0},"scala.collection.immutable.VectorIterator",{Ng:1,ob:1,c:1,pb:1,da:1,ca:1,id:1});function Sf(){Hf.call(this);this.Tc=null;this.Db=!1;this.Ia=null}Sf.prototype=new If;Sf.prototype.constructor=Sf;function yb(a){var b=new Sf;b.Tc=a;a=(new ef).a();Hf.prototype.He.call(b,a,!1,null);b.Db=!0;b.Ia="";return b}Sf.prototype.b=B({Xe:0},"java.lang.JSConsoleBasedPrintStream",{Xe:1,Gh:1,Fh:1,Td:1,c:1,Rd:1,Sd:1,Oe:1});function Ob(){this.J=null}Ob.prototype=new Qf;
Ob.prototype.constructor=Ob;Ob.prototype.a=function(){T.prototype.a.call(this);return this};Ob.prototype.b=B({qg:0},"scala.collection.Seq$",{qg:1,Xa:1,Wa:1,la:1,ea:1,c:1,ma:1,fa:1});var Nb=void 0;function Tf(){this.J=null}Tf.prototype=new Qf;Tf.prototype.constructor=Tf;function Uf(){}Uf.prototype=Tf.prototype;function Vf(){Jf.call(this);this.pa=this.oa=0}Vf.prototype=new Kf;Vf.prototype.constructor=Vf;function pb(a,b){var c=new Vf;c.oa=a;c.pa=b;Jf.prototype.Ie.call(c,null,null);return c}
Vf.prototype.b=B({xf:0},"scala.Tuple2$mcDD$sp",{xf:1,Ph:1,c:1,ni:1,lb:1,r:1,g:1,e:1,oi:1});function Wf(){this.y=null}Wf.prototype=new C;Wf.prototype.constructor=Wf;function Z(){}Z.prototype=Wf.prototype;Wf.prototype.k=h("y");Wf.prototype.B=function(){return za(this)};function Xf(){this.Ya=this.Va=this.Ta=null}Xf.prototype=new C;Xf.prototype.constructor=Xf;function Yf(){}Yf.prototype=Xf.prototype;function Zf(){this.ie=this.J=null}Zf.prototype=new Uf;Zf.prototype.constructor=Zf;
Zf.prototype.a=function(){T.prototype.a.call(this);$f=this;this.ie=(new Se).a();return this};Zf.prototype.b=B({ig:0},"scala.collection.IndexedSeq$",{ig:1,hd:1,Xa:1,Wa:1,la:1,ea:1,c:1,ma:1,fa:1});var $f=void 0;function fb(){$f||($f=(new Zf).a());return $f}function ag(){this.ta=this.Ab=0;this.na=null}ag.prototype=new qf;ag.prototype.constructor=ag;ag.prototype.O=function(){this.ta>=this.Ab&&Pb().zb.O();var a=this.na.qa(this.ta);this.ta=1+this.ta|0;return a};
function bg(a,b){var c=new ag;c.Ab=b;if(null===a)throw Pd(Td(),null);c.na=a;c.ta=0;return c}ag.prototype.U=function(){return this.ta<this.Ab};ag.prototype.b=B({kg:0},"scala.collection.IndexedSeqLike$Elements",{kg:1,ob:1,c:1,pb:1,da:1,ca:1,yi:1,g:1,e:1});function eb(){this.J=null}eb.prototype=new Uf;eb.prototype.constructor=eb;eb.prototype.a=function(){T.prototype.a.call(this);return this};eb.prototype.b=B({xg:0},"scala.collection.immutable.IndexedSeq$",{xg:1,hd:1,Xa:1,Wa:1,la:1,ea:1,c:1,ma:1,fa:1});
var db=void 0;function Rd(){S.call(this);this.ra=null}Rd.prototype=new gf;Rd.prototype.constructor=Rd;p=Rd.prototype;p.za=m("JavaScriptException");p.xa=m(1);p.gb=function(){this.stackdata=this.ra;return this};p.ya=function(a){switch(a){case 0:return this.ra;default:throw(new V).p(""+a);}};p.k=function(){return ja(this.ra)};p.N=function(a){this.ra=a;S.prototype.V.call(this,null,null);return this};p.B=function(){return id(this)};p.Ua=function(){return Cf(this)};
p.b=B({ic:0},"scala.scalajs.js.JavaScriptException",{ic:1,wa:1,va:1,W:1,c:1,e:1,lb:1,r:1,g:1});function Lc(){this.y=null}Lc.prototype=new Z;Lc.prototype.constructor=Lc;Lc.prototype.a=function(){this.y="Boolean";return this};Lc.prototype.b=B({Kf:0},"scala.reflect.ManifestFactory$BooleanManifest$",{Kf:1,ba:1,c:1,H:1,G:1,F:1,C:1,g:1,e:1,r:1});var Kc=void 0;function xc(){this.y=null}xc.prototype=new Z;xc.prototype.constructor=xc;xc.prototype.a=function(){this.y="Byte";return this};
xc.prototype.b=B({Lf:0},"scala.reflect.ManifestFactory$ByteManifest$",{Lf:1,ba:1,c:1,H:1,G:1,F:1,C:1,g:1,e:1,r:1});var wc=void 0;function Bc(){this.y=null}Bc.prototype=new Z;Bc.prototype.constructor=Bc;Bc.prototype.a=function(){this.y="Char";return this};Bc.prototype.b=B({Mf:0},"scala.reflect.ManifestFactory$CharManifest$",{Mf:1,ba:1,c:1,H:1,G:1,F:1,C:1,g:1,e:1,r:1});var Ac=void 0;function Jc(){this.y=null}Jc.prototype=new Z;Jc.prototype.constructor=Jc;Jc.prototype.a=function(){this.y="Double";return this};
Jc.prototype.b=B({Nf:0},"scala.reflect.ManifestFactory$DoubleManifest$",{Nf:1,ba:1,c:1,H:1,G:1,F:1,C:1,g:1,e:1,r:1});var Ic=void 0;function Hc(){this.y=null}Hc.prototype=new Z;Hc.prototype.constructor=Hc;Hc.prototype.a=function(){this.y="Float";return this};Hc.prototype.b=B({Of:0},"scala.reflect.ManifestFactory$FloatManifest$",{Of:1,ba:1,c:1,H:1,G:1,F:1,C:1,g:1,e:1,r:1});var Gc=void 0;function Dc(){this.y=null}Dc.prototype=new Z;Dc.prototype.constructor=Dc;Dc.prototype.a=function(){this.y="Int";return this};
Dc.prototype.b=B({Pf:0},"scala.reflect.ManifestFactory$IntManifest$",{Pf:1,ba:1,c:1,H:1,G:1,F:1,C:1,g:1,e:1,r:1});var Cc=void 0;function Fc(){this.y=null}Fc.prototype=new Z;Fc.prototype.constructor=Fc;Fc.prototype.a=function(){this.y="Long";return this};Fc.prototype.b=B({Qf:0},"scala.reflect.ManifestFactory$LongManifest$",{Qf:1,ba:1,c:1,H:1,G:1,F:1,C:1,g:1,e:1,r:1});var Ec=void 0;function $(){Xf.call(this);this.Ba=null}$.prototype=new Yf;$.prototype.constructor=$;function cg(){}cg.prototype=$.prototype;
$.prototype.k=h("Ba");$.prototype.B=function(){return za(this)};function zc(){this.y=null}zc.prototype=new Z;zc.prototype.constructor=zc;zc.prototype.a=function(){this.y="Short";return this};zc.prototype.b=B({Uf:0},"scala.reflect.ManifestFactory$ShortManifest$",{Uf:1,ba:1,c:1,H:1,G:1,F:1,C:1,g:1,e:1,r:1});var yc=void 0;function Nc(){this.y=null}Nc.prototype=new Z;Nc.prototype.constructor=Nc;Nc.prototype.a=function(){this.y="Unit";return this};
Nc.prototype.b=B({Vf:0},"scala.reflect.ManifestFactory$UnitManifest$",{Vf:1,ba:1,c:1,H:1,G:1,F:1,C:1,g:1,e:1,r:1});var Mc=void 0;function dg(){this.jf=this.J=null}dg.prototype=new Qf;dg.prototype.constructor=dg;dg.prototype.a=function(){T.prototype.a.call(this);eg=this;this.jf=(new re).a();return this};dg.prototype.b=B({Ag:0},"scala.collection.immutable.List$",{Ag:1,Xa:1,Wa:1,la:1,ea:1,c:1,ma:1,fa:1,g:1,e:1});var eg=void 0;function Qb(){eg||(eg=(new dg).a());return eg}function Zb(){this.J=null}
Zb.prototype=new Qf;Zb.prototype.constructor=Zb;Zb.prototype.a=function(){T.prototype.a.call(this);return this};Zb.prototype.b=B({Hg:0},"scala.collection.immutable.Stream$",{Hg:1,Xa:1,Wa:1,la:1,ea:1,c:1,ma:1,fa:1,g:1,e:1});var Yb=void 0;function Pc(){$.call(this)}Pc.prototype=new cg;Pc.prototype.constructor=Pc;Pc.prototype.a=function(){this.Ba="Any";var a=Nf(),b=Rb();this.Ta=a;this.Va=z(D);this.Ya=b;return this};
Pc.prototype.b=B({If:0},"scala.reflect.ManifestFactory$AnyManifest$",{If:1,nb:1,mb:1,c:1,H:1,G:1,F:1,C:1,g:1,e:1,r:1});var Oc=void 0;function Tc(){$.call(this)}Tc.prototype=new cg;Tc.prototype.constructor=Tc;Tc.prototype.a=function(){this.Ba="AnyVal";var a=Nf(),b=Rb();this.Ta=a;this.Va=z(D);this.Ya=b;return this};Tc.prototype.b=B({Jf:0},"scala.reflect.ManifestFactory$AnyValManifest$",{Jf:1,nb:1,mb:1,c:1,H:1,G:1,F:1,C:1,g:1,e:1,r:1});var Sc=void 0;function Vc(){$.call(this)}Vc.prototype=new cg;
Vc.prototype.constructor=Vc;Vc.prototype.a=function(){this.Ba="Nothing";var a=Nf(),b=Rb();this.Ta=a;this.Va=z(bf);this.Ya=b;return this};Vc.prototype.b=B({Rf:0},"scala.reflect.ManifestFactory$NothingManifest$",{Rf:1,nb:1,mb:1,c:1,H:1,G:1,F:1,C:1,g:1,e:1,r:1});var Uc=void 0;function Xc(){$.call(this)}Xc.prototype=new cg;Xc.prototype.constructor=Xc;Xc.prototype.a=function(){this.Ba="Null";var a=Nf(),b=Rb();this.Ta=a;this.Va=z(Wd);this.Ya=b;return this};
Xc.prototype.b=B({Sf:0},"scala.reflect.ManifestFactory$NullManifest$",{Sf:1,nb:1,mb:1,c:1,H:1,G:1,F:1,C:1,g:1,e:1,r:1});var Wc=void 0;function Rc(){$.call(this)}Rc.prototype=new cg;Rc.prototype.constructor=Rc;Rc.prototype.a=function(){this.Ba="Object";var a=Nf(),b=Rb();this.Ta=a;this.Va=z(D);this.Ya=b;return this};Rc.prototype.b=B({Tf:0},"scala.reflect.ManifestFactory$ObjectManifest$",{Tf:1,nb:1,mb:1,c:1,H:1,G:1,F:1,C:1,g:1,e:1,r:1});var Qc=void 0;
function fg(){this.sc=this.J=null;this.Sh=this.Hh=0}fg.prototype=new Uf;fg.prototype.constructor=fg;fg.prototype.a=function(){T.prototype.a.call(this);gg=this;this.sc=(new mb).Eb(0,0,0);return this};fg.prototype.b=B({Lg:0},"scala.collection.immutable.Vector$",{Lg:1,hd:1,Xa:1,Wa:1,la:1,ea:1,c:1,ma:1,fa:1,g:1,e:1});var gg=void 0;function gb(){gg||(gg=(new fg).a());return gg}function hg(){}hg.prototype=new C;hg.prototype.constructor=hg;function ig(){}ig.prototype=hg.prototype;
hg.prototype.qb=function(a,b,c,e){return td(this,a,b,c,e)};hg.prototype.jc=function(){var a=Ta(ka(this)),b;A();b=a;var c=Md(46);b=b.lastIndexOf(c)|0;-1!==b&&(a=a.substring(1+b|0));b=Ld(A(),a,36);-1!==b&&(a=a.substring(0,b));return a};function jg(){}jg.prototype=new ig;jg.prototype.constructor=jg;function lg(){}lg.prototype=jg.prototype;jg.prototype.sa=function(a){for(var b=this.ua();b.U();)a.P(b.O())};function mg(){}mg.prototype=new lg;mg.prototype.constructor=mg;function ng(){}ng.prototype=mg.prototype;
mg.prototype.k=function(){var a=this.jc()+"(";return this.qb((new zf).a(),a,", ",")").I.z};function og(){}og.prototype=new ng;og.prototype.constructor=og;function pg(){}pg.prototype=og.prototype;function qg(){}qg.prototype=new ng;qg.prototype.constructor=qg;function rg(){}p=rg.prototype=qg.prototype;p.P=function(a){throw(new V).p(""+(a|0));};p.sa=function(){};p.ua=function(){var a=new Df;a.nh=this;return a};p.X=m(0);p.B=function(){return ie(this)};p.jc=m("List");
function mb(){this.hb=this.fb=this.Aa=0;this.vc=!1;this.xb=0;this.Lc=this.Ic=this.Fc=this.Cc=this.zc=this.wc=null}mb.prototype=new ng;mb.prototype.constructor=mb;p=mb.prototype;p.j=h("Fc");p.qa=function(a){var b=a+this.Aa|0;if(0<=a&&b<this.fb)a=b;else throw(new V).p(""+a);return Ad(this,a,a^this.hb)};p.D=h("xb");p.P=function(a){return this.qa(a|0)};p.Eb=function(a,b,c){this.Aa=a;this.fb=b;this.hb=c;this.vc=!1;return this};p.Na=g("Lc");p.s=h("wc");p.w=h("Ic");p.t=g("Cc");
p.ua=function(){var a=(new Rf).n(this.Aa,this.fb);nb(a,this,this.xb);if(this.vc){var b=this.hb,c=-1+a.D()|0;switch(c){case 5:a.Na(R(a.S()));a.R(R(a.w()));a.A(R(a.j()));a.t(R(a.h()));a.l(R(a.f()));a.S().d[31&b>>25]=a.w();a.w().d[31&b>>20]=a.j();a.j().d[31&b>>15]=a.h();a.h().d[31&b>>10]=a.f();a.f().d[31&b>>5]=a.s();break;case 4:a.R(R(a.w()));a.A(R(a.j()));a.t(R(a.h()));a.l(R(a.f()));a.w().d[31&b>>20]=a.j();a.j().d[31&b>>15]=a.h();a.h().d[31&b>>10]=a.f();a.f().d[31&b>>5]=a.s();break;case 3:a.A(R(a.j()));
a.t(R(a.h()));a.l(R(a.f()));a.j().d[31&b>>15]=a.h();a.h().d[31&b>>10]=a.f();a.f().d[31&b>>5]=a.s();break;case 2:a.t(R(a.h()));a.l(R(a.f()));a.h().d[31&b>>10]=a.f();a.f().d[31&b>>5]=a.s();break;case 1:a.l(R(a.f()));a.f().d[31&b>>5]=a.s();break;case 0:break;default:throw(new L).N(c);}}1<a.wb&&ob(a,this.Aa,this.Aa^this.hb);return a};p.l=g("zc");p.X=function(){return this.fb-this.Aa|0};p.R=g("Ic");p.f=h("zc");p.S=h("Lc");p.B=function(){return ie(this)};p.aa=g("xb");p.h=h("Cc");p.m=g("wc");p.A=g("Fc");
p.b=B({Kg:0},"scala.collection.immutable.Vector",{Kg:1,Nb:1,Mb:1,Ob:1,c:1,$b:1,ac:1,dc:1,bc:1,da:1,ca:1,Ub:1,Xb:1,Tb:1,cc:1,Vb:1,Pb:1,Qb:1,Wb:1,r:1,Yb:1,Lb:1,ga:1,Rb:1,Sb:1,Zb:1,Mi:1,Fg:1,yg:1,Jg:1,mf:1,cd:1,dd:1,id:1,g:1,e:1,zi:1});function sg(){}sg.prototype=new rg;sg.prototype.constructor=sg;p=sg.prototype;p.a=function(){return this};p.za=m("Nil");p.xa=m(0);p.ya=function(a){throw(new V).p(""+a);};p.Ua=function(){return Cf(this)};
p.b=B({Dg:0},"scala.collection.immutable.Nil$",{Dg:1,zg:1,Nb:1,Mb:1,Ob:1,c:1,$b:1,ac:1,dc:1,bc:1,da:1,ca:1,Ub:1,Xb:1,Tb:1,cc:1,Vb:1,Pb:1,Qb:1,Wb:1,r:1,Yb:1,Lb:1,ga:1,Rb:1,Sb:1,Zb:1,Ni:1,Fg:1,yg:1,Jg:1,mf:1,Ai:1,Bi:1,lb:1,Ci:1,e:1,g:1});var tg=void 0;function Rb(){tg||(tg=(new sg).a());return tg}function ug(){}ug.prototype=new pg;ug.prototype.constructor=ug;function vg(){}vg.prototype=ug.prototype;function zf(){this.I=null}zf.prototype=new pg;zf.prototype.constructor=zf;p=zf.prototype;
p.a=function(){zf.prototype.Ee.call(this,16,"");return this};p.qa=function(a){a=65535&(this.I.z.charCodeAt(a)|0);return ae(a)};p.P=function(a){a=65535&(this.I.z.charCodeAt(a|0)|0);return ae(a)};p.ld=function(a,b){return this.I.z.substring(a,b)};p.k=function(){return this.I.z};p.sa=function(a){pd(this,a)};p.ua=function(){return bg(this,this.I.z.length|0)};p.Ee=function(a,b){zf.prototype.Je.call(this,Q((new U).o((b.length|0)+a|0),b));return this};p.X=function(){return this.I.z.length|0};
p.Je=function(a){this.I=a;return this};function vd(a,b){var c=a.I;A();Q(c,null===b?"null":ja(b));return a}p.B=function(){return ie(this)};p.b=B({Vg:0},"scala.collection.mutable.StringBuilder",{Vg:1,Og:1,Nb:1,Mb:1,Ob:1,c:1,$b:1,ac:1,dc:1,bc:1,da:1,ca:1,Ub:1,Xb:1,Tb:1,cc:1,Vb:1,Pb:1,Qb:1,Wb:1,r:1,Yb:1,Lb:1,ga:1,Rb:1,Sb:1,Zb:1,Tg:1,Sg:1,Xg:1,of:1,Ug:1,Pg:1,kf:1,Vc:1,Uc:1,Qg:1,cd:1,dd:1,Rg:1,Oi:1,lg:1,ti:1,T:1,jd:1,gd:1,fd:1,g:1,e:1});function N(){this.Da=null}N.prototype=new vg;
N.prototype.constructor=N;p=N.prototype;p.qa=function(a){return this.Da[a]};p.P=function(a){return this.Da[a|0]};p.sa=function(a){pd(this,a)};p.ua=function(){return bg(this,this.Da.length|0)};p.X=function(){return this.Da.length|0};p.B=function(){return ie(this)};function lb(a,b){a.Da=b;return a}p.jc=m("WrappedArray");
p.b=B({$g:0},"scala.scalajs.js.WrappedArray",{$g:1,Pi:1,Og:1,Nb:1,Mb:1,Ob:1,c:1,$b:1,ac:1,dc:1,bc:1,da:1,ca:1,Ub:1,Xb:1,Tb:1,cc:1,Vb:1,Pb:1,Qb:1,Wb:1,r:1,Yb:1,Lb:1,ga:1,Rb:1,Sb:1,Zb:1,Tg:1,Sg:1,Xg:1,of:1,Ug:1,Pg:1,kf:1,Vc:1,Ri:1,Si:1,gd:1,fd:1,Ki:1,Di:1,Li:1,Qg:1,cd:1,dd:1,Rg:1,Qi:1,Ti:1,lg:1,jd:1});
}).call(this);
//# sourceMappingURL=augmented-reality-with-scala-js-opt.js.map
